package(default_visibility = ["//visibility:public"])

cc_library(
    name = "FileIO",
    srcs = ["FileIO.cpp"],
    hdrs = ["FileIO.hpp"],
    deps = ["//Models:TreeLasso"],
)

cc_library(
    name = "DataBaseCommunicator",
    srcs = ["DataBaseCommunicator.cpp"],
    hdrs = ["DataBaseCommunicator.hpp"],
)
