new_http_archive(
    name = "gtest",
    url = "https://googletest.googlecode.com/files/gtest-1.7.0.zip",
    sha256 = "247ca18dd83f53deb1328be17e4b1be31514cedfc1e3424f672bf11fd7e0d60d",
    build_file = "gtest.BUILD",
    strip_prefix = "gtest-1.7.0",
)

#new_http_archive(
#	name = "eigen",
#	url = "https://bitbucket.org/eigen/eigen/get/3.2.7.tar.gz",
#	sha256 = "5a50a006f83480a31f1f9beabec9e91dad95138df19363ee73ccf57676f10405",
#	build_file = "eigen.BUILD",
#	strip_prefix = "eigen-eigen-b30b87236a1b",
#)

